import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ApolloProviders from "@/provider/apollo-provider";
import ClientLayout from "./client-layout"; // ⬅️ Import the client wrapper
import { BasketProvider } from "@/context/basletContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloProviders>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <BasketProvider>
            <ClientLayout>{children}</ClientLayout>
          </BasketProvider>
        </body>
      </ApolloProviders>
    </html>
  );
}
